load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@llvm//:defs.bzl", "exec_test")
load("@llvm//toolchain:selects.bzl", "platform_llvm_binary")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

alias(
    name = "llvm-readelf",
    actual = platform_llvm_binary("llvm-readelf"),
)

cc_binary(
    name = "hello",
    srcs = ["main.c"],
)

platform(
    name = "linux_x86_64_musl_pie_on",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
        "//constraints/cxxstdlib:libcxx",
        "//constraints/libc:musl",
        "//constraints/pie:on",
    ],
)

platform(
    name = "linux_aarch64_musl_pie_on",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
        "//constraints/cxxstdlib:libcxx",
        "//constraints/libc:musl",
        "//constraints/pie:on",
    ],
)

platform_transition_binary(
    name = "hello_x86_64_musl",
    binary = ":hello",
    target_platform = "@llvm//platforms:linux_x86_64_musl",
)

platform_transition_binary(
    name = "hello_x86_64_musl_pie_on",
    binary = ":hello",
    target_platform = ":linux_x86_64_musl_pie_on",
)

platform_transition_binary(
    name = "hello_x86_64_gnu",
    binary = ":hello",
    target_platform = "@llvm//platforms:linux_x86_64",
)

platform_transition_binary(
    name = "hello_aarch64_musl",
    binary = ":hello",
    target_platform = "@llvm//platforms:linux_aarch64_musl",
)

platform_transition_binary(
    name = "hello_aarch64_musl_pie_on",
    binary = ":hello",
    target_platform = ":linux_aarch64_musl_pie_on",
)

platform_transition_binary(
    name = "hello_aarch64_gnu",
    binary = ":hello",
    target_platform = "@llvm//platforms:linux_aarch64",
)

exec_test(
    sh_test,
    name = "x86_64_musl_static_pie_test",
    srcs = ["verify_static_pie.sh"],
    args = [
        "$(rootpath :llvm-readelf)",
        "$(rootpath :hello_x86_64_musl_pie_on)",
    ],
    data = [
        ":hello_x86_64_musl_pie_on",
    ],
    tools = [
        ":llvm-readelf",
    ],
)

exec_test(
    sh_test,
    name = "x86_64_musl_static_non_pie_default_test",
    srcs = ["verify_static_non_pie.sh"],
    args = [
        "$(rootpath :llvm-readelf)",
        "$(rootpath :hello_x86_64_musl)",
    ],
    data = [
        ":hello_x86_64_musl",
    ],
    tools = [
        ":llvm-readelf",
    ],
)

exec_test(
    sh_test,
    name = "x86_64_glibc_dynamic_non_pie_test",
    srcs = ["verify_dynamic_non_pie.sh"],
    args = [
        "$(rootpath :llvm-readelf)",
        "$(rootpath :hello_x86_64_gnu)",
    ],
    data = [
        ":hello_x86_64_gnu",
    ],
    tools = [
        ":llvm-readelf",
    ],
)

exec_test(
    sh_test,
    name = "aarch64_musl_static_pie_test",
    srcs = ["verify_static_pie.sh"],
    args = [
        "$(rootpath :llvm-readelf)",
        "$(rootpath :hello_aarch64_musl_pie_on)",
    ],
    data = [
        ":hello_aarch64_musl_pie_on",
    ],
    tools = [
        ":llvm-readelf",
    ],
)

exec_test(
    sh_test,
    name = "aarch64_musl_static_non_pie_default_test",
    srcs = ["verify_static_non_pie.sh"],
    args = [
        "$(rootpath :llvm-readelf)",
        "$(rootpath :hello_aarch64_musl)",
    ],
    data = [
        ":hello_aarch64_musl",
    ],
    tools = [
        ":llvm-readelf",
    ],
)

exec_test(
    sh_test,
    name = "aarch64_glibc_dynamic_non_pie_test",
    srcs = ["verify_dynamic_non_pie.sh"],
    args = [
        "$(rootpath :llvm-readelf)",
        "$(rootpath :hello_aarch64_gnu)",
    ],
    data = [
        ":hello_aarch64_gnu",
    ],
    tools = [
        ":llvm-readelf",
    ],
)
