exports_files([
    "bin/clang",
    "bin/clang++",
    "bin/clang-cpp",
    "bin/lld",
    "bin/ld.lld",
    "bin/ld64.lld",
    "bin/wasm-ld",
    "bin/llvm-ar",
    "bin/llvm-as",
    "bin/llvm-libtool-darwin",
    "bin/llvm-nm",
    "bin/llvm-objcopy",
    "bin/llvm-strip",
    # "bin/clang-tidy",
    # "bin/clang-format",
    "bin/clangd",
    # "bin/llvm-symbolizer",
    "bin/glibc-stubs-generator",
    # "bin/llvm-profdata",
    # "bin/llvm-cov",
    # "bin/llvm-dwp",
    # "bin/llvm-objdump",
])
