load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_go//go:def.bzl", "go_binary")
load(":defs.bzl", "force_pic_go_binary", "macos_arm64_debug_go_binary")

go_binary(
    name = "hello_cgo",
    srcs = ["hello.go"],
    cgo = True,
)

build_test(
    name = "hello_cgo_target_test",
    targets = [":hello_cgo"],
)

platform_transition_binary(
    name = "hello_cgo_x86_64_musl",
    binary = ":hello_cgo",
    target_platform = "@llvm//platforms:linux_x86_64_musl",
)

build_test(
    name = "hello_cgo_x86_64_musl_test",
    targets = [":hello_cgo_x86_64_musl"],
)

macos_arm64_debug_go_binary(
    name = "hello_cgo_macos_arm64",
    srcs = ["hello.go"],
    cgo = True,
)

build_test(
    name = "hello_cgo_macos_arm64_test",
    targets = [":hello_cgo_macos_arm64"],
)

force_pic_go_binary(
    name = "hello_cgo_force_pic",
    srcs = ["hello.go"],
    cgo = True,
)

platform_transition_binary(
    name = "hello_cgo_force_pic_x86_64_gnu",
    binary = ":hello_cgo_force_pic",
    target_platform = "@llvm//platforms:linux_x86_64",
)

build_test(
    name = "hello_cgo_force_pic_x86_64_gnu_test",
    targets = [":hello_cgo_force_pic_x86_64_gnu"],
)

platform_transition_binary(
    name = "hello_cgo_force_pic_x86_64_musl",
    binary = ":hello_cgo_force_pic",
    target_platform = "@llvm//platforms:linux_x86_64_musl",
)

build_test(
    name = "hello_cgo_force_pic_x86_64_musl_test",
    targets = [":hello_cgo_force_pic_x86_64_musl"],
)

# Build the cgo binary in the exec configuration
genrule(
    name = "hello_cgo_exec_run",
    outs = ["hello_cgo_exec_run.out"],
    cmd = "$(execpath :hello_cgo) > $@",
    tools = [":hello_cgo"],
)

build_test(
    name = "hello_cgo_exec_test",
    targets = [":hello_cgo_exec_run"],
)
