load("@llvm//runtimes/glibc/extension:make_select_glibc_repository_target.bzl", "declare_glibc_repository_target")

package(default_visibility = ["//visibility:public"])

declare_glibc_repository_target(
    name = "gnu_libc_headers",
    bazel_repository = "@glibc_headers",
    bazel_target = "gnu_libc_headers",
    target_compatible_with = ["@platforms//os:linux"],
)

declare_glibc_repository_target(
    name = "glibc_headers_directory",
    bazel_repository = "@glibc_headers",
    bazel_target = "glibc_headers_directory",
    target_compatible_with = ["@platforms//os:linux"],
)

declare_glibc_repository_target(
    name = "glibc_c_nonshared.static",
    bazel_repository = "@glibc",
    bazel_target = "c_nonshared",
    target_compatible_with = ["@platforms//os:linux"],
)

declare_glibc_repository_target(
    name = "glibc_Scrt1.object",
    bazel_repository = "@glibc",
    bazel_target = "glibc_Scrt1.object",
    target_compatible_with = ["@platforms//os:linux"],
)

declare_glibc_repository_target(
    name = "glibc_crt1.object",
    bazel_repository = "@glibc",
    bazel_target = "glibc_crt1.object",
    target_compatible_with = ["@platforms//os:linux"],
)
