module(name = "llvm_version_selection")

bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "llvm", version = "")
local_path_override(
    module_name = "llvm",
    path = "../..",
)

LLVM_VERSION = "21.1.8"

llvm = use_extension("@llvm//extensions:llvm.bzl", "llvm")
llvm.version(llvm_version = LLVM_VERSION)
use_repo(llvm, "llvm-project")

toolchain = use_extension("@llvm//extensions:toolchain.bzl", "toolchain")
use_repo(toolchain, "llvm_toolchains")

register_toolchains("@llvm_toolchains//:all")
