TOOLCHAIN_BINARIES = [
    "c++filt",
    "clang",
    "clang++",
    "clang-cl",
    "clang-cpp",
    "clang-scan-deps",
    "dsymutil",
    "lld",
    "ld.lld",
    "ld64.lld",
    "lld-link",
    "wasm-ld",
    "llvm-addr2line",
    "llvm-ar",
    "llvm-bitcode-strip",
    "llvm-cgdata",
    "llvm-cxxfilt",
    "llvm-debuginfod-find",
    "llvm-dlltool",
    "llvm-dwp",
    "llvm-gsymutil",
    "llvm-ifs",
    "llvm-install-name-tool",
    "llvm-libtool-darwin",
    "llvm-lipo",
    "llvm-ml",
    "llvm-mt",
    "llvm-nm",
    "llvm-objcopy",
    "llvm-objdump",
    "llvm-otool",
    "llvm-ranlib",
    "llvm-rc",
    "llvm-readelf",
    "llvm-readobj",
    "llvm-size",
    "llvm-strip",
    "llvm-symbolizer",
    "llvm-windres",
    # "clang-tidy",
    # "clang-format",
    # "clangd",
    # "llvm-profdata",
    # "llvm-cov",
    "sancov",
]
