TOOLCHAIN_BINARIES = [
    "clang",
    "clang++",
    "clang-cpp",
    "lld",
    "ld.lld",
    "ld64.lld",
    "wasm-ld",
    "llvm-ar",
    "llvm-as",
    "llvm-dlltool",
    "llvm-libtool-darwin",
    "llvm-nm",
    "llvm-objcopy",
    "llvm-strip",
    # "clang-tidy",
    # "clang-format",
    "clangd",
    # "llvm-symbolizer",
    # "llvm-profdata",
    # "llvm-cov",
    # "llvm-dwp",
    # "llvm-objdump",
]
