# Thin libstdc++ config.h wrapper.
#
# GCC-source counterpart files under //runtimes/libstdcxx declare the checks.
# Local autoconf rules execute those checks and render the header.

load(
    "//runtimes/libstdcxx:configure.ac.bzl",
    "CONFIG_ENTRIES",
)
load(
    "//runtimes/libstdcxx/autoconf:autoconf_config.bzl",
    "autoconf_config",
)
load(
    "//runtimes/libstdcxx/autoconf:autoconf_hdr.bzl",
    "autoconf_hdr",
)

def libstdcxx_config_h(
        name,
        config_defines,
        gthr_headers,
        **kwargs):
    checks_name = name + "_checks"
    autoconf_config(
        name = checks_name,
        checks = config_defines + CONFIG_ENTRIES,
        probe_context_include_root_markers = {
            "gthreads": "bits/gthr.h",
        },
        probe_contexts = {
            "gthreads": gthr_headers,
        },
    )
    autoconf_hdr(
        name = name,
        dep = ":" + checks_name,
        header_comment = "Generated by @llvm//runtimes/libstdcxx:config_h.",
        include_guard = "LLVM_LIBSTDCXX_CONFIG_H",
        out = name + ".h",
        **kwargs
    )
